### ISSUE TITLE
Report button

### ISSUE THREAD

**Issue by Charlyzzz** [mumuki/mumuki-atheneum#138]
Perhaps it could be helpful to include a button that works as a warning to admins, reporting an exercise needs revision. This could be a simple way to:
* Maintaining top notch evaluation levels.
* Correct wrongly submitted exercises.

**Comment by iluetich** [comment]
I'm pretty sure this has already been implemented and it's a live feature. It works by sending a notification to the exercise's creator, more specifically at this URL: mumuki.io/{preferred locale}/exercises/{exercise id}/submissions/{submission id}. There's a yellow button called "Notify problem to author".

**Comment by flbulgarelli** [comment]
@Charlyzzz  please clarify the issue in order to understand whether what was described by @iluetich is what you are talking about or not.
