### ISSUE TITLE
Hints

### ISSUE THREAD

**Issue by Charlyzzz** [mumuki/mumuki-atheneum#139]
It **could**  be funny and help the experience to add scores and hints as a motivation technique.
In addition to the actual submission form, X numbers of hints (let's say 3 as an example) could be requested as help to people that tilted while solving.

The total valuation of the problem is disminished proportionally to the numbers of hits given.

Eg: Whole exercise without hints: 10 points.
      One hint used: 7 points.
      Two .... 

And so and so.

**Comment by flbulgarelli** [comment]
This is related to #261 issue. The gamification discussion should occur there.
