### ISSUE TITLE
Accumulative extra code

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#150]
A lot of times the extra code for an exercises is basically the concatenation of extra codes of all previous exercises; that occurs when the guide is aimed to build a solution to a big problem, in small steps. 

Instead of writing all the previous extra code in each exercise, we should have an `accumulative_flag` in the guide that builds that list of extra codes for us. 

This should be also available in CRUD and export format

**Comment by faloi** [comment]
+1 to this, would be very useful for Gobstones guides

**Comment by flbulgarelli** [comment]
Duplicated of #455
