### ISSUE TITLE
Expectations per guide

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-atheneum#192]
When a guide is a part of a course (i.e. a series of guides) you may want to discourage the usage of elements of the paradigm/language that haven't been introduced yet.

For those cases, having a way to define expectations for all the exercises would be great, so you don't have to repeat them on each one.

**Comment by flbulgarelli** [comment]
Since Atheneum does not have guide's CRUD anymore, and since it imports everything from Bibliotheca, there is nothing else to do here.
