### ISSUE TITLE
Reify extra code description

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#197]
Currently each exercise can have extra code. However, in order to let the user know about which code is available, we need to add this to the description. 

This is tedious, because you need to repeat things like "assume that you have the following functions available", which also pollutes the description. 

We could have a separate, initially collapsed section - like the hints - named 'Toolbox' or 'what do I already have?' which lists which bindings are available. 

Something even better would be able to infer expectations like `Not:HasBinding:foo`  from that list. @faloi would probably like that.

**Comment by faloi** [comment]
+1 to this, specially the last part.

I'm thinking that this could be completely automated, at least in Haskell
and soon in Gobstones too. What do you think?

**Comment by flbulgarelli** [comment]
Yup. 

Instead of providing extra description as a plain markdown, we could provide it as a more structured yaml, with a list of bindings and description, used to both generate markdown and expectations.

**Comment by faloi** [comment]
What I'm saying is: that could be calculated by parsing the extra code,
without needing an extra yml :smile:

**Comment by flbulgarelli** [comment]
It is not that easy. 

Not only because we should be able to parse all supported languages - which makes runner implementation more difficult - but also requires that parser to run also in the platform, in order to present that list of extra code to the user **before** the submission is sent. 

What is more, although you may add extra code, you may not expect the user to know all its details. And you are still not explaning what the extra code does, nor its which arguments it takes.

**Comment by faloi** [comment]
Agree. But I think that the Toolbox shouldn't be collapsed, because we actually want the student to use them.

**Comment by flbulgarelli** [comment]
Ok, you have got a point

**Comment by flbulgarelli** [comment]
Since we already have the visible extra code section, this feature is not really necessary right now. 

Moreover, after having writen dozens of guides, I don't feel adding manually such information to the description is that tedious.
