### ISSUE TITLE
Investigate about Blockly

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#199]
Analyze the effort that supporting such tools would require. 

It would allow to integrate block languages like https://github.com/hugoruscitti/pilas-engine-bloques.
 See https://github.com/google/blockly

**Comment by PalumboN** [comment]
:+1:

**Comment by flbulgarelli** [comment]
We are putting this on hold, supporting block languages is not on the immediate roadmap
