### ISSUE TITLE
Display "beta" and "new" labels as ribbons

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-atheneum#214]
Now they are being displayed in the same way as the "learning" label, but I think they shouldn't, because the meaning is quite unrelated.

We should pick a color and an icon for Beta (yellow/orange?) and another for New (blue?), so the user can quickly identify it.

Here is a way to do it using CSS transformations: https://unindented.org/articles/github-ribbon-using-css-transforms/

**Comment by jvillarejo** [comment]
@faloi  I want to test it, how can I change to Beta an exercise?

**Comment by faloi** [comment]
The flags are available on a per guide basis, and can be changed via the edit view of a guide you own, e.g. http://es.mumuki.io/guides/26/edit

**Comment by flbulgarelli** [comment]
Those labels have being removed in #405.

Closing
