### ISSUE TITLE
Create a way of automatically test guides on CI

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#224]
Since guides are just code, we could create something to "test" them:

* validate markdown is ok
* validate mandatory files are present
* validate files are not empty
* validate keys are present
* etc

That way we could remove the error reporting logic from platform.

**Comment by faloi** [comment]
Another possible validation: last exercise shouldn't have corollary

**Comment by faloi** [comment]
I'm thinking this could be implemented creating a gem with a few rake tasks, relying on mumukit.

**Comment by flbulgarelli** [comment]
Now bibliotheca and the editor are responsible for doing such validations. Closing
