### ISSUE TITLE
Gamification on Submission

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#261]
## Abstract

In order people to encourage exercise solving, we could give her points when an exercise or guide is completed. 

### Practice guides only

This feature should not be available to learning guides - such guides should not give you any points. 

### Points calculation

* The max of a guide is the sum of the max points of each exercise
* The total points earned when solving a guide is, likewise, the sum of total point earned in each exercise
* Each exercise knows its max points
   * Exercise writer should provide max points, or
   * Let the platform decide them based on guide position, or
   * Let the platform assign a default value of 10 
* The points earned by an exercise are based on number of submissions and exercise status:
    * errored, failed or aborted submissions get 0 points
    * passed with warnings submissions get half of passed submissions points
    * passed submissions  get:

```haskell
points submissions max
       | submissions <= 2 = max
       | submissions <= 11 = max - div ((submissions - 2) * max)  10
       | otherwise = 1
```

* The minimum maximum points for an exercise is 10
* Points earned and max points are always integer values

### Displaying results

When you finish a guide, the following should be displayed:

* Total points earned 
* Guide max points 
* User total points

**Comment by faloi** [comment]
@flbulgarelli don't you think this goes against our "the error is good" principle?

**Comment by flbulgarelli** [comment]
Yes and no, it mostly depends on how you present the idea. 

First of all, the platform will not explain the algorithm. So - unless you read this issue :stuck_out_tongue:  - user is not aware of how to get points. Maximum points for exercises will not shown, neither. And earned points should be shown only when you actually get points. 

This means, getting points is presented as a gain, but not getting them is not presenting as a lossing. My hypothesis is that gaining something will encourage people to continue going on. 

However, it is true It is just an hypothesis. It would be nice to be able to turn the display of such results on and off on a per guide basis - for example, learning guides should have this feature disabled.

**Comment by flbulgarelli** [comment]
Related to #139

**Comment by flbulgarelli** [comment]
Gamification is not a current need. 

We actually have found that even without gamification, it generated a good-enough level of engagement.
