### ISSUE TITLE
Marker/Link at the end of a guide

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-atheneum#274]
Today when you get to the last exercise of a guide, there is no feedback that you've correctly finished it, just the absence of "Next" button.

It would be motivating to have some "fireworks", some congratulations, and/or a button saying "finish, I want to see my overall results" and/or a button "Next Guide".

**Comment by aguspina** [comment]
@asanzo This is happening when you finish the last exercise of a guide, but you did not finish all exercises of the guide. We will fix it!

thanks!

**Comment by flbulgarelli** [comment]
@asanzo had you solved all exercises when you reached guide's end, as @aguspina suggested?

**Comment by flbulgarelli** [comment]
This feature has being implement a long time ago. Closing
