### ISSUE TITLE
Weird shift key behaviour on cellphones

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#281]
@epere4 said: 

> No se bien por qué, pero cuando estoy desde el celu en el cuadro de texto para escribir código (estaba probando los ejercicios de Mover(Norte)) y aprieto la tecla de mayúsculas sucede algo raro.
Pasa a modo mayúsculas como habría de esperarse, pero cuando la suelto me borra un caracter.
Es raro también que tengo que mantenerla apretada para que las teclas salgan en mayúscula. Es como que el cuadro de textos estuviera intentando hacer algo inteligente, pero no le sale bien. Tal vez desde desktop eso anda bien.

**Comment by faloi** [comment]
Duplicated in #487
