### ISSUE TITLE
SPA Exercises view

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-atheneum#306]
We could add this feature in some guides which exercises are incremental in order to improve user experience and reuse code of user' solution. @flbulgarelli @faloi @fedescarpa @jvillarejo  I would like to hear your opinions.

**Comment by faloi** [comment]
I don't get it, can you show us any example of what you expect?

**Comment by aguspina** [comment]
Yeah, you could try *Staying sharp with Angugalr.js* course in codeschool. The first level is free.

**Comment by flbulgarelli** [comment]
Could you provide a capture or - better - a mockup showing us how it should look?

**Comment by aguspina** [comment]
It's just a fade in fade out of exercise data => (description, title)

**Comment by flbulgarelli** [comment]
@aguspina can we close this?
