### ISSUE TITLE
Allow runners to provide expectation description

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-atheneum#312]
In order to start removing expectations description from the platform, we should allow the runner to provide the description of the failed expectations (right now they are at https://github.com/mumuki/mumuki-platform/blob/master/config/locales/expectations.es.yml).

My proposal is to give priority to the runner, and only search in the locales yml if the runner doesn't provide a translation.

**Comment by flbulgarelli** [comment]
Since all runners will support the same expectation language after mulang integration, this issue has no sense anymore.
