### ISSUE TITLE
Request additional information about user on registration

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#313]
Although it is not necessary in http://mumuki.io central platform, it is necessary to allow user to introduce additional information about herself when registering on a standalone platform.

That information should be configurable on a per-instance basis, and should be exposed to users API. That way, subscriber like the teacher tools will be able to assign a student to a course without manual intervention. 

That would allow to share a single mumuki instance across multiple courses.

**Comment by flbulgarelli** [comment]
@faloi  please comment.

**Comment by flbulgarelli** [comment]
Related to #313

**Comment by faloi** [comment]
I think we could start with name, surname and email, all of them required and private. The additional info could be useful, but right now we don't need it (do we?).

When this is done, I would send a notification to our current users, so they can provide their information.

**Comment by flbulgarelli** [comment]
This was resolved at classroom. Closing
