### ISSUE TITLE
License Policy

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#316]
We should develop a license policy, and add licenses to all repositories. For example, we could use the following: 
- Creative Commons for Content
- MIT for runners
- GPL for core components: platform, teacher tools, authoring tool, etc. 

I would like to hear your opinions @faloi @aguspina @PalumboN @fedescarpa

**Comment by flbulgarelli** [comment]
See http://choosealicense.com/

**Comment by faloi** [comment]
Sounds good to me. 

We just have to decide if the content is considered software or not (I really don't know). In case it's not software, I think we should use a Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) license.

**Comment by faloi** [comment]
To sum up, each repo should have a LICENSE file, consistent with the gemspec file (if it exists). Not sure how to deal with the guides.

**Comment by flbulgarelli** [comment]
Let's use CC BY-SA as suggested with guides

**Comment by aguspina** [comment]
Agree with you, CC for guides and contents, but why not GPL for runners too?

**Comment by flbulgarelli** [comment]
Runners are not meaningful by themselves, so I really don't care about their usage outside the context of Mumuki Platform. If someone want's to  use them in a non free context, good for her. 

And that allows runner's code to be linked with non-free technology, also.

**Comment by flbulgarelli** [comment]
OK., I take this issue, I will add the license notices to all our code. 

However, from now on, we should add the copyright notice to each file. I will create a separate issue for that.

**Comment by faloi** [comment]
> However, from now on, we should add the copyright notice to each file. I will create a separate issue for that.

Are you _really_ sure that is necessary?

**Comment by flbulgarelli** [comment]
> > However, from now on, we should add the copyright notice to each file. I will create a separate issue for that.

> Are you really sure that is necessary?

Yes, it is. Please have a look at the GPL license. It states the following: 

```
  If you develop a new program, and you want it to be of the greatest
possible use to the public, the best way to achieve this is to make it
free software which everyone can redistribute and change under these terms.

  To do so, attach the following notices to the program.  It is safest
to attach them to the start of each source file to most effectively
state the exclusion of warranty; and each file should have at least
the "copyright" line and a pointer to where the full notice is found.
```

Aside of that, it is an standard practice. Just you need to setup your IDE to do so :wink:

**Comment by faloi** [comment]
We can close this one, can't we?

**Comment by flbulgarelli** [comment]
Yes.
