### ISSUE TITLE
Extended Architecture

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#354]
There are some problems that, in order to be addressed, may require a new architecture.  They are: 

* Bidirectional sync from local platform instances to a remote platform instance. 
* Consumption of mumuki content from an IDE - we need to be able to download mumuki guides, and submit solutions, and be able to query user's progress. 
* Preferences handling, that may be consumed by IDEs linked with mumuki. For example, preferences regarding code style that may be set by teacher
* Adding or removing a guide to multiple instances

I am submitting this isue in order to freely discuss alternatives

**Comment by flbulgarelli** [comment]
@faloi @javierfernandes @npasserini

**Comment by aguspina** [comment]
Firebase?

**Comment by flbulgarelli** [comment]
This will probably require adding new nodes and publishing new APIs, that extend the current ones:

* submissions web hook, which notifies submissions
* guides and users endpoints, which retrieves guides and users

**Comment by flbulgarelli** [comment]
After some offline discussion, we agree this will require some refactors and additions. 

They are: 

## Sync Component

Create a component that is polymorphic with a platform but just adds a cache in order to allow bidirectional sync of an offline platform/ide **submissions** with an online platform. This component might be replaced by a firebase  connection.
 
## Content Server

This should a be a multitenant server that allows **content** -  guides - sync among platforms and IDE's, preferences distribution, centralized storage of guides, and a simple api for a content editor for storing guides, so that it does not need to deal with git complexities. 

* Extract a service that converts github repos to a guide json forth and back. This code should be extracted from current platform. 
* Create a service that stores guides in a json DB, notifies platforms when there are updates, and exposes an api for consuming them
*  Create a service that stores preferences per course and tenant
*  Create a service that allows association of a guide to one or more tenants and courses
* Manage permissions

Some of this parts may be partially replaced by firebase, too. 

## Auth server

We need to maintain a consistent user - students and teachers - across multiple platforms and IDEs, and allows offline login.

**Comment by flbulgarelli** [comment]
Now that we have introduced Auth0 as SSO solution, and that bibliotheca is our working content-server, we can consider this issue closed by now. 

A sync component should be discussed separately
