### ISSUE TITLE
Add QSim support

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-atheneum#372]
[QSim](https://github.com/molinarirosito/QSim) is an Assembly-like language, designed at UNQ for learning about computer architecture.

A first approach could be: given an initial registry state and a student's solution, verify that a final registry state is reached.

**Comment by flbulgarelli** [comment]
Good. @nnydjesus seems to be a contributor there, we could bother him :stuck_out_tongue:

**Comment by flbulgarelli** [comment]
This is being addressed here https://github.com/Orga-UNQ/mumuki-qsim-server
