### ISSUE TITLE
Navbar Allignment issues 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#415]
This is subtle, but there are a few scenarios where the alignment of Logo, login button, profile image and/or big Mu is not ok. 

![badallignment](https://cloud.githubusercontent.com/assets/677436/12449797/968d0edc-bf5e-11e5-92a7-c41b23387665.png)
![badallignment2](https://cloud.githubusercontent.com/assets/677436/12449801/9804b60c-bf5e-11e5-8b1d-d6047c8c814f.png)
![badallignment1](https://cloud.githubusercontent.com/assets/677436/12449804/99b21a4e-bf5e-11e5-926f-fa31cd6ceb7c.png)

**Comment by aguspina** [comment]
@flbulgarelli I really don't know how did you get the first scenario. You are not suppose to get that page without being authenticated

**Comment by flbulgarelli** [comment]
> @flbulgarelli I really don't know how did you get the first scenario. You are not suppose to get that page without being authenticated

@aguspina yes, you are right. But this is wrong, we should be able to display that page even if user is not logged in. I am going to send such change as a PR in the next hours
