### ISSUE TITLE
Error fatal al intentar reiniciar password

### ISSUE THREAD

**Issue by huenu** [mumuki/mumuki-atheneum#445]
Me encontré con un error al querer reiniciar la password en el editor del atheneo. Entiendo que el email que puse es válido (mdalponte@unq.edu.ar)

Texto que se muestra (no da detalles del error):
"
Ups, algo no anduvo bien....

Algo se rompió feo en Mumuki. Y necesitamos solucionarlo urgentemente.

¡Por favor contanos cómo te pasó esto!
"

**Comment by flbulgarelli** [comment]
Esto no debería estar pasando ahora.  
@huenu , si te vuelve a ocurrir, por favor reabrí este issue.

Gracias!
