### ISSUE TITLE
Mumuki returns a 500 when accessing to assignments

### ISSUE THREAD

**Issue by AivanGuevara** [mumuki/mumuki-atheneum#450]
When trying to access my assignments, i get an Internal Server Error (500), redirecting me to the error page after that.

Steps to reproduce bug:
1) Log in
2) Go to the profile
3) Go to "recent activities"

**Comment by flbulgarelli** [comment]
Thanks for reporting the issue. 

I am not being able to reproduce it. @fedescarpa @faloi could you check with your users?

**Comment by fedescarpa** [comment]
it worked to me

**Comment by flbulgarelli** [comment]
User assignment pages were deprecated and have being removed today. 

If you need to review an student progress, please consider using mumuki classroom tools.
