### ISSUE TITLE
Update to ace version that includes Gobstones and Wollok highlighting

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-atheneum#459]
A new release [has been made](https://github.com/ajaxorg/ace/releases/tag/v1.2.3), we can now update the version.

**Comment by faloi** [comment]
Oops, https://github.com/codykrieger/ace-rails-ap has not released anything... :weary:

**Comment by flbulgarelli** [comment]
And the won't probably do it as fast as we need. We can always fork

**Comment by faloi** [comment]
I've just created an [issue](https://github.com/codykrieger/ace-rails-ap/issues/18) there, let's see if they answer...
