### ISSUE TITLE
Expectation not working

### ISSUE THREAD

**Issue by PalumboN** [mumuki/mumuki-atheneum#464]
[This exercise](http://mumuki.io/exercises/1627-funcional-alternativas-guardas-y-patrones-variable-anonima) says that this solution:
```Haskell
estadoDeAnimo "Viernes" = "¡Estoy enamorado!"
estadoDeAnimo otroDia =  "Meh :S"
```
pass all expectations:
- estadoDeAnimoHasBinding
- estadoDeAnimoNot:HasGuards
- **estadoDeAnimoHasAnonymousVariable**

But I'm not using anonymous variable

**Comment by flbulgarelli** [comment]
Fixed.
