### ISSUE TITLE
Nombre al crear classroom con parte duplicada

### ISSUE THREAD

**Issue by sanuzzi** [mumuki/mumuki-atheneum#466]
Si se crea una classroom cuyo nombre comience con "pdep-utn" (o lo correspondiente a cada materia), produce un nombre con esa parte duplicada en el listado de cursos. Ya van 3 cursos que nos vimos tentados de escribir eso, y luego no se puede cambiar.

Tres primeras alternativas que se me ocurren:
- Que a la izquierda del input esté fijo ese texto, indicando que el nombre va a comenzar así, que sea visible.
- Que en el listado de cursos se diferencie lo que corresponde a la materia, respecto del curso en sí. Quizá dividiendo el nombre en dos. Así evitamos la tentativa de escribir todo junto al crear otro nuevo.
- Que se pueda cambiar el nombre luego de crearlo.

**Comment by faloi** [comment]
This issue was moved to mumuki/mumuki-teacher-tools#30
