### ISSUE TITLE
Playground exercises are being shown as problem exercises

### ISSUE THREAD

**Issue by ArielUmansky** [mumuki/mumuki-atheneum#468]
I'm not sure if this is the correct repo to report this error, but I didn't find any visible repo for some kind of "editor" or "content-editor". 

As the title describes, some exercises are being shown as problem exercises even though they are configured as playgrounds. Am I doing something wrong?

![1](https://cloud.githubusercontent.com/assets/1649905/13901912/6a19185e-ee12-11e5-8a6c-864f16f97d3d.png)

Here's the configuration: 

![2](https://cloud.githubusercontent.com/assets/1649905/13901917/95109190-ee12-11e5-9168-ec30dd34ff65.png)

**Comment by flbulgarelli** [comment]
Fixed

![playgroundwollok](https://cloud.githubusercontent.com/assets/677436/13954211/8f5b6e56-f01e-11e5-86ee-ac30393a474c.png)
