### ISSUE TITLE
Guide editor should link to the published guide

### ISSUE THREAD

**Issue by mgarciaisaia** [mumuki/mumuki-atheneum#470]
Once a guide gets published in Mumuki, the Guide Editor should link to the actual "live" version of the guide - so one doesn't have to _search for it_ on the index.

Somewhere in this screen, I mean:

<img width="1168" alt="screen shot 2016-03-21 at 3 40 00 pm" src="https://cloud.githubusercontent.com/assets/1190974/13929898/3a1643a6-ef7b-11e5-86cb-616737bac32a.png">

**Comment by flbulgarelli** [comment]
Related to #465 

We need in both cases to provide a canonical reference to the exercise and guide

**Comment by flbulgarelli** [comment]
![links](https://cloud.githubusercontent.com/assets/677436/14089137/a757d180-f509-11e5-91b6-a0c0863e1ad1.png)

@mgarciaisaia done, it will be deployed in a few minutes. From now on, please report classroom and editor issues to https://github.com/mumuki/mumuki-teacher-tools/issues
