### ISSUE TITLE
The "assignments" page doesn't work for some users

### ISSUE THREAD

**Issue by J9794** [mumuki/mumuki-atheneum#471]
It sends me to the error page if I try to enter to my assignments, and I tried with different IDs, some work and some doesn't.
Some users' assignment page that work for me:
http://mumuki.io/users/1314/assignments
http://mumuki.io/users/1309/assignments
http://mumuki.io/users/666/assignments
http://mumuki.io/users/102/assignments
http://mumuki.io/users/13/assignments
Some that doesn't work:
http://mumuki.io/users/5/assignments
http://mumuki.io/users/1/assignments
http://mumuki.io/users/860/assignments
http://mumuki.io/users/363/assignments
http://mumuki.io/users/899/assignments

**Comment by flbulgarelli** [comment]
Hi @J9794 

Thank you for reporting the issue. 

Currently that pages are deprecated and are going to be removed in the short-time. If you want to follow-up some student, please consider using Mumuki Classroom
