### ISSUE TITLE
Create new guide from editor doesn't work

### ISSUE THREAD

**Issue by PalumboN** [mumuki/mumuki-atheneum#473]
I'm trying to create a new guide from mumuki editor but it throws this error:
```
undefined method `name' for #<Mumukit::Service::Slug:0x00000004431e40>
```

Then the guide appears in the editor but I can't modify it, and the repo's not been created.

**Comment by flbulgarelli** [comment]
Fixed. Please check now @PalumboN 

From now on, please use https://github.com/mumuki/mumuki-teacher-tools  for reporting issues on editor or classroom

Regar

**Comment by PalumboN** [comment]
Working :D 
And ok.

Thanks!
