### ISSUE TITLE
[Classroom] Static load time is taking a lot

### ISSUE THREAD

**Issue by Charlyzzz** [mumuki/mumuki-atheneum#474]
Perhaps it's an ISP issue, couldn't tell. Look at these times!

[img-20160327-wa0009](https://cloud.githubusercontent.com/assets/7073356/14090426/a9b31528-f510-11e5-9d22-178516a30de3.jpg)

They have been consistently that bad since Sunday. Console shows no errors.

**Comment by flbulgarelli** [comment]
Fixed.
