### ISSUE TITLE
Long exercise titles break into different columns in the guide's main page

### ISSUE THREAD

**Issue by matifreyre** [mumuki/mumuki-atheneum#477]
If you look at this guide: http://pdep-utn.mumuki.io/guides/206-tp-funcional-1-sabados-manana-series-de-tv
You'll notice that some exercises in the "content" part at the bottom have their links split in more than one row. That by itself is not an issue, but the problem arises when these rows get to be in different columns, like item 4 in that guide, which renders it confusing:
![image](https://cloud.githubusercontent.com/assets/10454118/14118113/40771114-f5be-11e5-953b-9d996be95602.png)

**Comment by flbulgarelli** [comment]
Hi @matifreyre 

There is not neat solution to such problem. Actually the problem there is that the exercise title is too long (45 characters).

We should probably limit the length of an exercise title to, say 35 characters, and/or truncate the exercises title with an elipsis if it exceeds such length. 

Anyway, I recommend shortening such exercise titles.

**Comment by flbulgarelli** [comment]
> We should probably limit the length of an exercise title to, say 35 characters, and/or truncate the exercises title with an elipsis if it exceeds such length.

See https://github.com/mumuki/mumuki-teacher-tools/issues/7
