### ISSUE TITLE
Classroom - Feature: "open in atheneum" from solution view

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-atheneum#478]
Right now when in Classroom I open a guide to see its students' submissions, I see a link "Abrir en atheneum". This link is very useful.
Yet it'd be grat if you could have that link also in the view where I see the student solution for an exercise. A use case I do a lot is: 
Get into a guide to see a student submission -> Look for the student -> Look for the solution -> Watch the solution and realize I forgot a detail about the exercise text -> press back -> press "Abrir en atheneum" -> look for the exercise and click it -> read the text

I'd very much like to have this shortened by getting a link to the exercise itself, and not for the entire guide.

**Comment by faloi** [comment]
This issue was moved to mumuki/mumuki-teacher-tools#28
