### ISSUE TITLE
Classroom - Feature: "Notify me of new submissions" button

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-atheneum#480]
Yeah, it's feature tuesday. Sorry. I'm excited.
Sometimes we teachers like to follow the progress of a student in certain exercise or in certain guide. I'd like to have a check button to activate notifications when a student submitts a new solution.

Reeeeally low priority, though. Just dreaming.

**Comment by asanzo** [comment]
Duplicated here:
https://github.com/mumuki/mumuki-teacher-tools/issues/6

**Comment by flbulgarelli** [comment]
Closing per previous comment

**Comment by flbulgarelli** [comment]
Related to #235
