### ISSUE TITLE
Haskell Console: Being able to use :t

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-atheneum#482]
In GHCi, I can do:
```Haskell
Prelude> :t "hola"
"hola" :: [Char]
```
Yet in Mumuki console I get:
```Haskell
Prelude> :t "hola"
/tmp/compilation58:7:22: parse error on input ‘:’
```
Nothing I can't live without, but it's a cool tool for teaching and type debugging.

**Comment by PalumboN** [comment]
I thought that this feature doesn't exist because there are exercises where the student must explicit the function's type.
Anyway we could block this type of query in that exercises.... Or not :P

**Comment by flbulgarelli** [comment]
This is not actually that simple - we are emulating the haskell console by running haskell programs, and not by using the actual GHCi. 

That means we should implement that type inferring tool by hand. We could use something as described here: 

http://stackoverflow.com/questions/10399685/haskell-getting-the-static-type-of-an-expression

I really think this is an interesting feature, but it is not in our short term roadmap. @PalumboN would you like to investigate about it and add that feature to hspec-server? You have  already worked on that repo, so you know its code is quite straight forward :wink:

**Comment by flbulgarelli** [comment]
It would be awesome if we could be able to deactivate in a per-request basis.

**Comment by PalumboN** [comment]
> @PalumboN would you like to investigate about it and add that feature to hspec-server?

Yes! :star2:

**Comment by flbulgarelli** [comment]
Moving to runner repo https://github.com/mumuki/mumuki-hspec-server2/issues/1
