### ISSUE TITLE
Measure Sumbission Time

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-atheneum#491]
If we could measure how long did it take to solve an exercise (or at least how much did it take between two sumbissions) that could give us interesting usage data.
Actually, I thought this as a consequence of having certain doubts about if the pupils really read the purely theoretical exercises (with no coding needed).

Just an idea, not important.

**Comment by flbulgarelli** [comment]
We could easily show the submission date for each student's solution. That may work for you, right?

**Comment by flbulgarelli** [comment]
This is issue should go to mumuki/mumuki-teacher-tools
