### ISSUE TITLE
Problema en mumuki

### ISSUE THREAD

**Issue by rudolphOne** [mumuki/mumuki-atheneum#524]
Estaba trabajando en mumuki (http://pdp-unsam.mumuki.io/guides/4-logico-practica-hechos-y-reglas) y me aparece un mensaje de error. Creo que estando fuera del editor oprimi dos veces la tecla backspace y apareció el mensaje de error.

**Comment by flbulgarelli** [comment]
Hola!

Gracias por avisar, estuvimos haciendo actualizaciones durante la mañana. El problema ya debería estar resuelto, pero si volvés a tenerlo, no dudes en avisar. 

Saludos
