### ISSUE TITLE
Inicio de sesión

### ISSUE THREAD

**Issue by sserantes** [mumuki/mumuki-atheneum#536]
Solo intente iniciar sesión con GitHub y funciono hasta que me solicito permisos para ver mi dirección de correo electrónico, después de la confirmación dio el fallo.

**Comment by flbulgarelli** [comment]
Hola!

No estoy pudiendo reproducir el problema. Qué mensaje de error te mostró @sserantes  ?

**Comment by sserantes** [comment]
Lamentablemente no tome una captura de pantalla, pero parecía mas bien un mensaje genérico. De todas formas con un segundo intento ingrese sin problemas, creo que esta pestaña estuvo abierta en mi navegador varios días y fue hoy que se me ocurrió hacer el primer inicio de sesión.
Quizá no sea posible reproducir el problema.
Estoy de acuerdo en cerrar el issue cuando lo creas conveniente.

**Comment by flbulgarelli** [comment]
Perfecto, si te vuelva a pasar algo similar, no dudes en reportarlo. 

Gracias por la ayuda :smile: !
