### ISSUE TITLE
Problema en mumuki - No se puede entrar a las guías complementarias

### ISSUE THREAD

**Issue by rudolphOne** [mumuki/mumuki-atheneum#539]
Buen día, no puedo ingresar a esta pagina, http://pdp-unsam.mumuki.io/guides/219-trabajos-practicos-logico-show-max,
Saludos.

Rodolfo

**Comment by flbulgarelli** [comment]
Buenas!

Estamos trabajando en eso, en un rato volverá a la normalidad

**Comment by flbulgarelli** [comment]
@rudolphOne resuelto. 

Ahora la nueva url para tu es http://pdep-utn.mumuki.io/complements/1-logico-show-max

**Comment by rudolphOne** [comment]
Hola Franco!, probé la nueva url y me sigue apareciendo la página de error.

Saludos.

Rodolfo

2016-05-08 12:30 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:

**Comment by flbulgarelli** [comment]
Buenas!

Podés probar de nuevo?

Tanto la nueva URL:

http://pdp-unsam.mumuki.io/complements/1-logico-show-max

como la vieja URL: 

 http://pdp-unsam.mumuki.io/guides/219-trabajos-practicos-logico-show-max

deberían funcionar. 

Probá ambas por favor.

**Comment by flbulgarelli** [comment]
@rudolphOne igonrá mi comentario anterior. 

Encontramos el bug. En breve lo solucionamos

**Comment by rudolphOne** [comment]
Hola Franco, ahi esta funcionando! Gracias !!

Saludos

Rodolfo

2016-05-08 17:08 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:

**Comment by flbulgarelli** [comment]
Genial, no me diste tiempo a responder :stuck_out_tongue:
