### ISSUE TITLE
Error al acceder ejercicios TP2

### ISSUE THREAD

**Issue by ivanaBenitez** [mumuki/mumuki-atheneum#543]
Luego de acceder al link:

 http://pdep-utn.mumuki.io/guides/215-tp-fun-2-sabados-manana-series-de-t2

 si se elige algún ejercicio se presenta un error que no permite continuar:

![image](https://cloud.githubusercontent.com/assets/19254609/15099889/30a51656-1539-11e6-931c-e8ed675dde77.png)

**Comment by flbulgarelli** [comment]
Buenas @ivanaBenitez !

Fijate ahora, el problema debería estar solucionado. 

Saludos!
