### ISSUE TITLE
No se puede acceser al TP1 Logico Unsam

### ISSUE THREAD

**Issue by nicosab83** [mumuki/mumuki-atheneum#544]
No se puede acceder a los ejercicios (x4) del TP1 Logico unsam.
http://pdp-unsam.mumuki.io/complements/1-logico-show-max

**Comment by flbulgarelli** [comment]
Resuelvo.

**Comment by flbulgarelli** [comment]
Probá ahora por favor, @nicosab83

**Comment by nicosab83** [comment]
No quedo solucionado, sigue apareciendo el cartel.
Entro aca:
http://pdp-unsam.mumuki.io/complements/1-logico-show-max
Aprieto ¨Segui Aprendiendo¨
Y aparece un cartel que dice:
Ups, algo no anduvo bien....
Algo se rompió feo en Mumuki. Y necesitamos solucionarlo urgentemente.
¡Por favor contanos cómo te pasó esto!

**Comment by flbulgarelli** [comment]
> Aprieto ¨Segui Aprendiendo¨

Gracias, esto creo que es la clave del problema. Ese botón no debería aparecer allí, ya que si terminaste de hacer los 4 ejercicios de `show max`, no hay nada mas para hacer después. 

Probá ahora por favor

**Comment by nicosab83** [comment]
Es que no los complete los 4, me falta el ultimo.
Ahora puedo entrar del 1 al 3, el 4to me tira el error.
http://pdp-unsam.mumuki.io/exercises/2370-logico-show-max-salir-a-vender

**Comment by flbulgarelli** [comment]
Una más, y no jodemos más.....

Probá ahora por favor @nicosab83

**Comment by nicosab83** [comment]
Perfecto !!!! Pude entrar.
Muchas gracias.

**Comment by flbulgarelli** [comment]
Gracias a a vos por la ayuda!
