### ISSUE TITLE
se cayo y no levanto nunca mas

### ISSUE THREAD

**Issue by sergio087** [mumuki/mumuki-atheneum#551]
http://pdep-utn.mumuki.io/guides/137-funcional-guia-monadas

Creo q estaba resolviendo el punto 10

**Comment by flbulgarelli** [comment]
Ahí lo levanto :smile:

**Comment by flbulgarelli** [comment]
http://iasc.mumuki.io/lessons/39-programacion-funcional-avanzada-funcional-guia-monadas
