### ISSUE TITLE
Ignore Warning: Clauses are not together in the source-file

### ISSUE THREAD

**Issue by PalumboN** [mumuki/mumuki-atheneum#561]
Can we ignore the `Warning: Clauses are not together in the source-file` for _Prolog_ solutions?

I have cases where the students must add new clauses for a given predicate or in particulars exercises adding examples in extra code. This warning appears until the exercise is done and it's very annoying and confused.

**Comment by flbulgarelli** [comment]
This is a plunit-runner issue: 

https://github.com/mumuki/mumuki-plunit-server

Please reopen it there. 

And if you wan't to fix it, be our guest :smile:

**Comment by PalumboN** [comment]
Oh, sorry. https://github.com/mumuki/mumuki-plunit-server/issues/18

> And if you wan't to fix it, be our guest :smile:

:+1: rnr!
