### ISSUE TITLE
Sign out user when no permissions in private organization

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-atheneum#567]

**Comment by flbulgarelli** [comment]
I don't think this is a good idea. If you enter by accident in an incorrect url, you get logged off - you just did a get and it had a visible, surprising effect.

**Comment by flbulgarelli** [comment]
Related to #579

**Comment by flbulgarelli** [comment]
Closing without changes.

If you change an organization private settings, simply invalidating all sessions will do the trick. Not ideal, but it works.
