### ISSUE TITLE
problema al cambiar de ejercicio

### ISSUE THREAD

**Issue by AxelFulop** [mumuki/mumuki-atheneum#586]
estaba haciendo el ejercicio 5.9 de la guia de logico y quise ir a la guia 5 y me tira un error,
 Ups!, algo no anduvo bien....

Algo se rompió feo en Mumuki. Y necesitamos solucionarlo urgentemente

**Comment by faloi** [comment]
@aguspina ?

**Comment by flbulgarelli** [comment]
Hola @AxelFulop ,

a qué URL estás accediendo? mumuki.io o pdep-utn.mumuki.io? Si se trata del segundo caso, te registraste con el usuario que estás utilizando en pdep-utn.classroom.mumuki.io?

**Comment by flbulgarelli** [comment]
Related to #579

**Comment by AxelFulop** [comment]
Hola, me pasaba en crhome , en Firefox no me tiraba ningún problema, lo volví a usar en crhome y sin ningún problema, la verdad ni idea que había pasado,accedi con el Dr Pdep mumuki y  estaba usando  el usuario de pdep

**Comment by flbulgarelli** [comment]
Gracias!
