### ISSUE TITLE
Horrible Inexpressive Error: Prolog missing end of sentence

### ISSUE THREAD

**Issue by asanzo** [mumuki/mumuki-atheneum#591]
When I forget the point (.) at the end of a clause...

`cuadrado(X,Y):- Y is X * X`

It'd be great to have a better error:

```
ERROR: /tmp/mumuki.compile20160602-3-151a36u:15:15: Syntax error: Operator priority clash
ERROR: /tmp/mumuki.compile20160602-3-151a36u:2:
    test cuadrado(4, 16): received error: plunit_mumuki_submission_test:'unit body'/2: Undefined procedure: plunit_mumuki_submission_test:cuadrado/2
ERROR: /tmp/mumuki.compile20160602-3-151a36u:6:
    test cuadrado(2, 4): received error: plunit_mumuki_submission_test:'unit body'/2: Undefined procedure: plunit_mumuki_submission_test:cuadrado/2
ERROR: /tmp/mumuki.compile20160602-3-151a36u:10:
    test cuadrado(10, 100): received error: plunit_mumuki_submission_test:'unit body'/2: Undefined procedure: plunit_mumuki_submission_test:cuadrado/2
```

**Comment by flbulgarelli** [comment]
Hi @asanzo 

This is a https://github.com/mumuki/mumuki-plunit-server issue. Please report such issues there

**Comment by flbulgarelli** [comment]
@asanzo feedback has been added for some scenarios where it is highly probable that the error is a missing dot. 

However, SWI Prolog parser produces many similar errors that are difficult to distinguish. So the proposed fix does not cover all the possible scenarios.

**Comment by flbulgarelli** [comment]
![no-dot](https://cloud.githubusercontent.com/assets/677436/15761798/8db54404-28f0-11e6-9aa1-487df79bd37e.png)
