### ISSUE TITLE
Login problem: students already registered are not allowed to solve an exam

### ISSUE THREAD

**Issue by fdodino** [mumuki/mumuki-atheneum#595]
This students

Nicolás Pérez <niperez1992@gmail.com>
joaquin mazoud <joaquinmazoud@gmail.com>

belong to "K2053 - viernes noche" course.

They try to access this exam: http://pdep-utn.mumuki.io/exams/f778b629dfe9e1f2
getting a message "You have no permission".

They tried to register to  the course
but a message "Student already exist" is shown.
Entering incognito mode didn't work.

Fede Scarpa thinks this is due to an auth0 login problem using different social networks...
redoing authentication login (html file) could help.

**Comment by flbulgarelli** [comment]
@aguspina @fedescarpa can we investigate and close this issue? Or at least give a definitive answer to what is happening here? 

I am quite confident that those users are trying to use wrong accounts, but I would like to be sure about that. 

If there is an usability issue - probable there is - lets propose a solution in a separate ticket.

**Comment by flbulgarelli** [comment]
Answered by private message
