### ISSUE TITLE
Missing Editor in URL

### ISSUE THREAD

**Issue by danaluz** [mumuki/mumuki-atheneum#604]
The url  http://mumuki.io/exercises/1723-programacion-funcional-listas-textos has missing the editor and the console.

**Comment by flbulgarelli** [comment]
Hi @danaluz 

I am seeing the editor and the console properly. Is this still happening to you? Could you please provide an screenshot?

**Comment by danaluz** [comment]
Hi @flbulgarelli, I upload the screenshot, this just happened now while I was trying to move forward in the exercises. Nonetheless, this situation is intermitent, it doesn't happen all the time, but a refresh in the page does not fix it.
![errormumuki](https://cloud.githubusercontent.com/assets/17326274/16292275/40e91bb8-38e6-11e6-90bb-6b7849f8f760.PNG)

**Comment by flbulgarelli** [comment]
Thanks @danaluz.

We will fix it today. Sorry for the inconvenience

**Comment by flbulgarelli** [comment]
Done. Please check now.
