### ISSUE TITLE
Cannot enter to exersices's statements

### ISSUE THREAD

**Issue by JuanchiRios** [mumuki/mumuki-atheneum#605]
When i try to enter to exersices's statements, for example http://pdep-utn.mumuki.io/exercises/2014-programacion-logica-practica-inversibilidad-equipo-abandono, I get a 403 error
> es decir que no estás autorizado a ver este contenido. ¿Puede que hayas ingresado con una cuenta incorrecta?

Or this error

> algo se rompió feo en Mumuki. Y necesitamos solucionarlo 

I'm login with my gmail account, the same I use in the classroom.

**Comment by flbulgarelli** [comment]
Hi!

This first error message is not an issue. You should contact the administrator as states in the message box.  You have probably not being registered in the classroom as a teacher. 

Regarding the second error message, it may be an issue, but we need more details about how it happened.  Please expand that description or close this issue until it happens again.

**Comment by flbulgarelli** [comment]
@JuanchiRios did this issue happened again? Can we close it?

**Comment by JuanchiRios** [comment]
@flbulgarelli No it didn't , close it :stuck_out_tongue:

**Comment by flbulgarelli** [comment]
Thanks!
