### ISSUE TITLE
Si trato de rehacer un ejercicio...

### ISSUE THREAD

**Issue by gobstones-admin** [mumuki/mumuki-atheneum#606]
...que me da por terminado, y aprieto "Enviar", llego a un estado de error.
FF

**Comment by aguspina** [comment]
Deactivating account linking. Closing

**Comment by flbulgarelli** [comment]
Hola @gobstones-admin no estamos pudiendo reproducir este problema. 

Te sigue pasando? Nos podrías pasar una descripción más detallada del mensaje o una captura de pantalla?

**Comment by gobstones-admin** [comment]
Me llega este mail solo, y no recuerdo lo que escribí. ¿Me describen lo que
escribí, o me mandan un link?
FF

2016-08-08 16:36 GMT-03:00 Franco Leonardo Bulgarelli <
notifications@github.com>:

**Comment by faloi** [comment]
No tiene sentido mantener esta issue que nunca se pudo reproducir, cierro.
