### ISSUE TITLE
Group guides by paradigm

### ISSUE THREAD

**Issue by JuanchiRios** [mumuki/mumuki-atheneum#607]
It would be really nice if there was a way to group guide by paradigm. In certain way you are already doing this by putting a prolog or haskell icon in the guides. 
The motivation is that in two months when a teacher enter to the classroom to correct some OOP exercise, he will not be interested in see all others guides. Maybe you could have like expandables folders or something like that

**Comment by flbulgarelli** [comment]
Hi @JuanchiRios please report this issue in teacher-tools. It is related to https://github.com/mumuki/mumuki-teacher-tools/issues/106
