### ISSUE TITLE
Filter by exercises in the classroom

### ISSUE THREAD

**Issue by JuanchiRios** [mumuki/mumuki-atheneum#608]
Now in the classroom you only can filter by guide. It always happen to me that i know the name of the exercise but not the name of guide, so i need to look in what guide the exercise is. This could be solve if the filter in the classroom look for exercises too and not only for guides

**Comment by flbulgarelli** [comment]
Hi, @JuanchiRios please remember to report this issue in the proper tracker https://github.com/mumuki/mumuki-teacher-tools

**Comment by flbulgarelli** [comment]
See https://github.com/mumuki/mumuki-teacher-tools/issues/113
