### ISSUE TITLE
Problema Login Facebook

### ISSUE THREAD

**Issue by lspir** [mumuki/mumuki-atheneum#611]
Error al acceder con Login de Facebook copio email recibido:

>  Quiero entrar a mumuki pero me tira error, anoche este ejercicio (alHorrno) me tiraba el error: Request Timeout, ahora no puedo loguear, te adjunto una imagen del error que me sale ahora.
pd: intente borrando las cokies del navegador pero me pasa lo mismo.

El error que se muestra en Facebook es el siguiente:

![mumuki](https://cloud.githubusercontent.com/assets/7250853/16276587/655e5000-3885-11e6-8b7d-5f31d9ae3b1b.png)

**Comment by flbulgarelli** [comment]
Probá ahora por favor!
