### ISSUE TITLE
Link to Functional Programming Guide too slow

### ISSUE THREAD

**Issue by roli93** [mumuki/mumuki-atheneum#612]
When I enter to Mumuki.io and click on "Capítulo 2: Programación Funcional" it starts loading and takes over 5 seconds to get to the page.

**Comment by flbulgarelli** [comment]
It seems that the problem is a DB bottleneck. That page is loading all the exercises of a whole chapter - more than 300 in this case - all it's lessons, and all the progress for each exercise. See a development rails log for it: 


```
I, [2016-06-16T15:27:20.515558 #17457]  INFO -- :   Rendered chapters/show.html.erb within layouts/application (36567.0ms)
I, [2016-06-16T15:27:22.922825 #17457]  INFO -- : Completed 200 OK in 39011ms (Views: 34589.9ms | ActiveRecord: 4415.8ms)
......

I, [2016-06-16T15:27:57.059814 #8691]  INFO -- :   Rendered chapters/show.html.erb within layouts/application (27911.9ms)
I, [2016-06-16T15:28:00.223022 #8691]  INFO -- : Completed 200 OK in 31110ms (Views: 28259.9ms | ActiveRecord: 2837.2ms)
....
```

This means that not only those queries are taking a lot, but also that rendering is too heavy

**Comment by flbulgarelli** [comment]
We should try fragment cache's

http://guides.rubyonrails.org/caching_with_rails.html#fragment-caching

This could be applied also to homepage and some sections of editor page

**Comment by flbulgarelli** [comment]
@roli93 we have added some cache to the chapter view.

We have tested it and there is a significant performance improvement. Please check now.

**Comment by flbulgarelli** [comment]
New logs from server: 

```
Completed 200 OK in 1659ms (Views: 1211.9ms | ActiveRecord: 435.0ms)
Completed 200 OK in 1583ms (Views: 1185.8ms | ActiveRecord: 390.9ms)
```

Compare to previous record: 

```
... (Views: 28259.9ms | ActiveRecord: 2837.2ms)
```

its a big performance boost!
