### ISSUE TITLE
Reloading an exercise copies the code from the previous exercise!

### ISSUE THREAD

**Issue by mmatos** [mumuki/mumuki-atheneum#635]
Ugly bug detected! I used F5 to refresh the page and the solution I had submitted was replaced with the code I submited for the previous exercise.

This happened with a Wollok guide (particularly http://pdep-utn.mumuki.io/lessons/79-programacion-con-objetos-colecciones), but I imagine it's not a Wollok specific issue.

**Comment by flbulgarelli** [comment]
Hi!

Sorry, I am not sure if I understood the issue. Could you please provide more specific details about how it happen? Is a reproductible issue or it happend randomly?

**Comment by flbulgarelli** [comment]
@mmatos

**Comment by mmatos** [comment]
Sorry, the other day was happening consistently, now I can't even reproduce it (?)

**Comment by flbulgarelli** [comment]
Nice :)

Please reopen if it happens again :smile:

**Comment by mmatos** [comment]
Ok, it happened again, it wasn't anytime I pressed F5, it only happens if I'm doing it over an excersice that I just edited through the Mumuki content editor (?)
