### ISSUE TITLE
Display guide authors somewhere

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-atheneum#652]

**Comment by flbulgarelli** [comment]
What about displaying such information in the guide view?

http://mumuki.io/lessons/8-programacion-funcional-valores-y-funciones

Perhaps it could be the last title, under `content`, and display only the main authors, with a link to another page with the long contributors section - in monotype font. For example: 

```markdown
## Authors 

This guide's content was developed by #{guide.main_authors} and [many others](http://mumuki.io/guides/#{guide.id}/contributors), and it is licencsed under [CC SA 4](link to license)
```

It is important the the authoring information is visible and easy to access, but without making the user lost focus on her main task. 

@faloi @aguspina @fedescarpa

**Comment by flbulgarelli** [comment]
Perhaps something like this? 

![screencapture-central-localmumuki-io-3000-lessons-25-fundamentos-practica-primeros-programas-1472580475357](https://cloud.githubusercontent.com/assets/677436/18101029/9c41c7ea-6ec3-11e6-9de3-cab82f311515.png)

**Comment by aguspina** [comment]
@flbulgarelli this issue already closed right?

**Comment by flbulgarelli** [comment]
Yes.
