### ISSUE TITLE
Replace exams with repeated guides

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-atheneum#660]
We need to considerate the posibility of a teacher who create 2 exams with the same guide, the solution proposed by @flbulgarelli is to replace the exam and do not consider the posibilitiy of 2 exams with same guide at the same time

**Comment by flbulgarelli** [comment]
@aguspina was this solved after the commands-queue refactor?

**Comment by aguspina** [comment]
No!

**Comment by aguspina** [comment]
@flbulgarelli please review
