### ISSUE TITLE
Editor doesn't appear sometimes

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-atheneum#668]
Happened to me at http://central.mumuki.io/exercises/2514-variables-ojo-te-pisa, with this error:

```js
// 2514-variables-ojo-te-pisa:252 Uncaught ReferenceError: $ is not defined
$('.progress-list-item.active').attr('class', "progress-list-item text-center success active");
```

It doesn't happen all the times, but a few reloads are enough to reproduce it.

**Comment by flbulgarelli** [comment]
Done in 1d6a069a8fbf8caf389c2c2e5be2c3d25f451e32
