### ISSUE TITLE
Bad interpolation in visible extra code

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-atheneum#689]
Seems like an attempt to add syntax highlighting...

![image](https://cloud.githubusercontent.com/assets/1585835/19969599/f86fec96-a1b7-11e6-9b25-d469fcad2a16.png)

I double-checked and it's ok on the editor:

![image](https://cloud.githubusercontent.com/assets/1585835/19969676/3cbf90d6-a1b8-11e6-8318-684e2891199b.png)

**Comment by faloi** [comment]
@flbulgarelli any news on this one? Also happens on C code (and probably all the other languages too).

**Comment by flbulgarelli** [comment]
I am fixing it right now
