### ISSUE TITLE
When showing the type of a function text "Haskell" confuses 

### ISSUE THREAD

**Issue by estefaniamiguel** [mumuki/mumuki-atheneum#693]
A user asked what that Haskell there meant

Should we remove it? Or is there an explanation?

![haskell](https://cloud.githubusercontent.com/assets/3276427/20112463/3922c8be-a5cb-11e6-8c78-279c558d7a2e.png)

**Comment by fedescarpa** [comment]
@estefaniamiguel It's a typo! 
I already corrected it. Refresh the exercise.
Thanks
