### ISSUE TITLE
The `rake db:seed` crashes if RabbitMQ is not installed, no matter if QUEUELESS_MODE=true

### ISSUE THREAD

**Issue by rodri042** [mumuki/mumuki-atheneum#701]

**Comment by flbulgarelli** [comment]
The problem is that the actual mode is named `MUMUKI_QUEUELESS_MODE`, not just `QUEUELESS_MODE`. 

I have checked using `MUMUKI_QUEUELESS_MODE`, and I couldn't reproduce the issue.
