### ISSUE TITLE
HTML roto

### ISSUE THREAD

**Issue by mpaulavb** [mumuki/mumuki-atheneum#719]
Hola!
Dejé sin terminar el ejercicio para continuarlo posteriormente y el html se rompió.
Gracias!
Paula

**Comment by flbulgarelli** [comment]
¡Hola!

¿Nos pasarías el link al ejercicio y una captura de pantalla?  

¡Gracias!

**Comment by mpaulavb** [comment]
Gracias! Ya lo pude resolver, pero me surgieron otras dudas:
-Cómo accedo a la biblioteca de procedimientos?-Cuál es la diferencia entre ejercicio y solución?
Saludos!Paula


      De: Franco Leonardo Bulgarelli <notifications@github.com>
 Para: mumuki/mumuki-atheneum <mumuki-atheneum@noreply.github.com> 
CC: mpaulavb <mpaulavblanco@yahoo.com.ar>; Author <author@noreply.github.com>
 Enviado: Sábado, 3 de diciembre, 2016 21:07:16
 Asunto: Re: [mumuki/mumuki-atheneum] HTML roto (#719)
   
¡Hola!¿Nos pasarías el link al ejercicio y una captura de pantalla?¡Gracias!—

**Comment by flbulgarelli** [comment]
> Gracias! Ya lo pude resolver, pero me surgieron otras dudas:

Buenísimo, entonces paso a cerrar este issue. 

> -Cuál es la diferencia entre ejercicio y solución?

La diferencia es que el _ejercicio_ es la actividad planteada, es "lo que hay que hacer", mientras que _solución_ es la resolución que propone el estudiante a un _ejercicio_. Además, hay distintos tipos de ejercicios, por ejemplo, _problemas_ y _áreas de juego_. 

> -Cómo accedo a la biblioteca de procedimientos?

Supongo que te referís a cómo ver el código (oculto) de la biblioteca que viene en algunos ejercicios. La respuesta en realidad varía según estés utilizando la herramienta como docente o estudiante:

* si es como estudiante, simplemente no se puede ver el código oculto de la biblioteca. 
* si es como docente, te recomiendo que des un vistazo a nuestro documento [Mumuki Para Docentes](https://docs.google.com/document/d/1TP-jiZCcMbSRXJajxMK0zmdrDEmx07zE5FNEiIvVT5g/edit)

Si tenés más consultas, ¡no dudes en escribirnos a info@mumuki.org! 

> Saludos!Paula

**Comment by mpaulavb** [comment]
Hola!
Está bien, hay ejercicios que me costaron acertar en la respuesta porque no aceptaban funciones definidas en ejercicios anteriores. O al revés, había que usar funciones previas y no lo aclaraba específicamente. Me pasaron un link donde hay un detalle un poco más preciso en algunos casos.
Muchas gracias por las aclaraciones!Saludos,Paula

      De: Franco Leonardo Bulgarelli <notifications@github.com>
 Para: mumuki/mumuki-atheneum <mumuki-atheneum@noreply.github.com> 
CC: mpaulavb <mpaulavblanco@yahoo.com.ar>; Author <author@noreply.github.com>
 Enviado: Miércoles, 7 de diciembre, 2016 1:23:05
 Asunto: Re: [mumuki/mumuki-atheneum] HTML roto (#719)
   

Gracias! Ya lo pude resolver, pero me surgieron otras dudas:
Buenísimo, entonces paso a cerrar este issue.
-Cuál es la diferencia entre ejercicio y solución?
La diferencia es que el ejercicio es la actividad planteada, es "lo que hay que hacer", mientras que solución es la resolución que propone el estudiante a un ejercicio. Además, hay distintos tipos de ejercicios, por ejemplo, problemas y áreas de juego.
-Cómo accedo a la biblioteca de procedimientos?
Supongo que te referís a cómo ver el código (oculto) de la biblioteca que viene en algunos ejercicios. La respuesta en realidad varía según estés utilizando la herramienta como docente o estudiante:   
   - si es como estudiante, simplemente no se puede ver el código oculto de la biblioteca.
   - si es como docente, te recomiendo que des un vistazo a nuestro documento Mumuki Para Docentes
Si tenés más consultas, ¡no dudes en escribirnos a info@mumuki.org!
Saludos!Paula
